In [28]:
#import packages
import geopandas as gpd, pandas as pd, os, numpy as np

# Section 1: Reading in the data and exploring using pandas and geopandas
## Read the Costa_Classification_Data_Cleaned2.csv file into a DataFrame

In [29]:
df=pd.read_csv('../Costa_Rica_Data/Costa_Classification_Data_Cleaned2.csv') ##../ in the relative path moves out of the templates directory into the CostaRica-Notebook directory

## Get basic information from the DataFrame

In [30]:
print(df.shape) #number of rows and columns
display(df.columns) #all column names

(101160, 44)

Index(['plotid', 'sampleid', 'Use', 'Cover', 'Vegetation', 'Herbaceous',
       'Grass', 'Cultivation', 'WetLand', 'Terrain', 'Water', 'Another Class',
       'SAF', 'Changes15_', 'Win_Lose', 'geometry', 'BLUE', 'GREEN', 'NIR',
       'RED', 'SWIR1', 'SWIR2', 'altura2', 'aspect', 'aspectcos', 'aspectdeg',
       'aspectYesn', 'brightness', 'clay_1mMed', 'diff', 'elevation', 'evi',
       'fpar', 'hand30_100', 'lai', 'mTPI', 'ndvi', 'ocs_1mMed', 'sand_1mMed',
       'savi', 'Yeslt_1mMed', 'slope', 'topDiv', 'wetness'],
      dtype='object')

### Split out response and predictor columns

In [31]:
id=['plotid', 'sampleid']

resp=['Use', 'Cover', 'Vegetation', 'Herbaceous',
       'Grass', 'Cultivation', 'WetLand', 'Terrain', 'Water', 'Another Class',
       'SAF']
pred=['BLUE', 'GREEN', 'NIR',
       'RED', 'SWIR1', 'SWIR2', 'altura2', 'aspect', 'aspectcos', 'aspectdeg',
       'aspectYesn', 'brightness', 'clay_1mMed', 'diff', 'elevation', 'evi',
       'fpar', 'hand30_100', 'lai', 'mTPI', 'ndvi', 'ocs_1mMed', 'sand_1mMed',
       'savi', 'Yeslt_1mMed', 'slope', 'topDiv', 'wetness']

### Look at summary stats for predictor columns

In [32]:
display(df[pred].describe()) #summary statistics for predictors
display(df[pred].isna().sum()) #number of NAs by column

,BLUE,GREEN,NIR,RED,SWIR1,SWIR2,altura2,aspect,aspectcos,aspectdeg,...,lai,mTPI,ndvi,ocs_1mMed,sand_1mMed,savi,Yeslt_1mMed,slope,topDiv,wetness
count,101130.000000,101134.000000,101134.000000,101134.000000,101134.000000,101134.000000,97181.000000,101160.000000,101160.000000,101160.000000,...,101160.000000,100982.000000,100792.000000,101160.000000,101160.000000,101134.000000,101160.000000,101160.000000,100982.000000,101134.000000
mean,0.028622,0.054576,0.326286,0.040583,0.167247,0.077850,22.636585,171.109960,0.537114,0.975305,...,0.424042,8129.081104,0.788556,66.426354,308.684732,0.488191,301.557198,11.868206,1324.070991,-0.014940
std,0.055628,0.053711,0.094669,0.055446,0.060418,0.040518,9.236450,105.641588,0.237923,0.293449,...,0.198097,37.876898,0.150143,19.969865,64.429899,0.121552,57.613569,10.272339,0.305253,0.048696
min,-0.188642,-0.069182,-0.008353,-0.080238,-0.000983,0.000777,0.000000,0.000000,0.073425,0.500000,...,0.000000,7891.000000,-0.974632,0.000000,0.000000,-0.142855,0.000000,0.000000,1323.644835,-0.277014
25%,0.016480,0.037215,0.267527,0.020220,0.129010,0.051542,16.000000,80.692791,0.331022,0.724147,...,0.245000,8116.000000,0.748902,55.000000,282.450000,0.425665,281.800000,3.380156,1323.770864,-0.036506
50%,0.022998,0.047225,0.325250,0.028910,0.162120,0.068180,22.000000,173.549553,0.555292,0.982082,...,0.500000,8128.000000,0.839014,63.000000,309.600000,0.506732,302.850000,8.711405,1324.046264,-0.005657
75%,0.030697,0.061738,0.384732,0.047005,0.200757,0.095433,30.000000,264.027390,0.749065,1.233409,...,0.615000,8139.000000,0.882352,73.000000,341.350000,0.571769,327.650000,17.920089,1324.330226,0.010607
max,1.063955,1.024878,0.980080,1.010193,0.562135,0.481972,51.000000,359.030029,0.877583,1.497306,...,0.670000,8390.000000,0.999941,150.000000,778.050000,0.902410,599.550000,72.676102,1324.630000,0.733936

BLUE             30
GREEN            26
NIR              26
RED              26
SWIR1            26
SWIR2            26
altura2        3979
aspect            0
aspectcos         0
aspectdeg         0
aspectYesn        0
brightness       26
clay_1mMed        0
diff             26
elevation         0
evi              30
fpar              0
hand30_100        3
lai               0
mTPI            178
ndvi            368
ocs_1mMed         0
sand_1mMed        0
savi             26
Yeslt_1mMed       0
slope             0
topDiv          178
wetness          26
dtype: int64

### Exercise 1: Explaining NAs
- Why does altura2 have so many NAs (hint look at altura2 data in geemap? Can a different value be substituted for the NAs? 
- Why does savi, wetness, diff, and brightness have 26 NAs?
- Why does topDiv have NAs?
- Why does NDVI have NAs?
- Why does mTPI have NAs?
- What would happen if we did not address the NAs?

### Addressing NA in predictors
Here we will make 2 assumptions
- altura2 nas should be changed to zero
- all other na will be removed

In [33]:
df.loc[df['altura2'].isna(),'altura2']=0 #set na to zero
df['altura2']
df2=df.dropna()

### Look at summary stats for response columns

In [34]:
display(df2[resp].describe()) #summary stats for response
display((df2[resp].isna()).sum())

,Use,Cover,Vegetation,Herbaceous,Grass,Cultivation,WetLand,Terrain,Water,Another Class,SAF
count,100614,100614,100614,100614,100614,100614,100614,100614,100614,100614,100614
unique,8,7,9,5,4,11,6,6,3,7,4
top,Forest,Vegetation,Tree,Not_Applicable,Not_Applicable,Not_Applicable,Not_Applicable,Forest,Not_Applicable,Not_Applicable,Not_Applicable
freq,58464,93811,60744,76196,77372,92235,96881,58439,99888,95203,92235

Use              0
Cover            0
Vegetation       0
Herbaceous       0
Grass            0
Cultivation      0
WetLand          0
Terrain          0
Water            0
Another Class    0
SAF              0
dtype: int64

### Exercise 2: Unique Categories
- What are the unique categories for each response column and their frequency of occurrence?
- How is Not_Applicable different from No Information?

### Look at summary stats for plot id columns

In [35]:
display(df2[id].describe()) #summary stats for response
display((df2[id].isna()).sum())
df_gr=df2[id].groupby('plotid')
cnt_sampleid=df_gr.agg('size')
display(np.unique(cnt_sampleid)) #display how many sampleid records are in each plotid
display(cnt_sampleid[cnt_sampleid > 9]) #display which plots have more than 9 records
display(df.loc[df['plotid']==1630]) #select just plot 1630 which sampleid to use

              plotid      sampleid
count  100614.000000  1.006140e+05
mean    86788.966406  3.471569e+05
std    258525.694957  1.034103e+06
min         2.000000  5.000000e+00
25%      2828.000000  1.131200e+04
50%      5634.000000  2.253850e+04
75%      8441.000000  3.376600e+04
max    910231.000000  3.640929e+06

plotid      0
sampleid    0
dtype: int64

array([ 1,  3,  4,  5,  6,  7,  8,  9, 18], dtype=int64)

plotid
1630    18
2175    18
3105    18
3150    18
3163    18
4607    18
6916    18
dtype: int64

,plotid,sampleid,Use,Cover,Vegetation,Herbaceous,Grass,Cultivation,WetLand,Terrain,...,lai,mTPI,ndvi,ocs_1mMed,sand_1mMed,savi,Yeslt_1mMed,slope,topDiv,wetness
89532,1630,6517,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.292445,52.0,286.75,0.194740,348.30,1.322494,1323.661862,-0.200940
89533,1630,6517,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.292445,52.0,286.75,0.194740,348.30,1.322494,1323.661862,-0.200940
89534,1630,6518,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.298658,52.0,286.75,0.184348,348.30,1.854334,1323.661862,-0.188596
89535,1630,6518,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.298658,52.0,286.75,0.184348,348.30,1.854334,1323.661862,-0.188596
89536,1630,6519,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.312833,52.0,286.75,0.195779,348.30,1.854334,1323.661862,-0.193918
89537,1630,6519,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.312833,52.0,286.75,0.195779,348.30,1.854334,1323.661862,-0.193918
89538,1630,6520,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.292577,52.0,286.75,0.190970,348.30,0.942981,1323.662105,-0.191193
89539,1630,6520,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.292577,52.0,286.75,0.190970,348.30,0.942981,1323.662105,-0.191193
89540,1630,6521,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.301933,52.0,286.75,0.196495,348.30,2.974677,1323.662105,-0.200302
89541,1630,6521,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.301933,52.0,286.75,0.196495,348.30,2.974677,1323.662105,-0.200302
89542,1630,6522,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.301598,52.0,286.75,0.198600,348.30,2.974679,1323.662105,-0.204489
89543,1630,6522,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.301598,52.0,286.75,0.198600,348.30,2.974679,1323.662105,-0.204489
89544,1630,6523,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.322541,52.0,294.40,0.211323,380.75,0.942981,1323.662105,-0.183218
89545,1630,6523,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.322541,52.0,294.40,0.211323,380.75,0.942981,1323.662105,-0.183218
89546,1630,6524,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.320008,52.0,294.40,0.202978,380.75,2.780288,1323.662105,-0.196244
89547,1630,6524,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.320008,52.0,294.40,0.202978,380.75,2.780288,1323.662105,-0.196244
89548,1630,6525,Agriculture,Vegetation,Another Vegetation,Not_Applicable,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.322724,52.0,294.40,0.207067,380.75,1.322496,1323.662105,-0.196752
89549,1630,6525,Agriculture,Vegetation,Herbaceous,Other_Herbaceous,Not_Applicable,Cana,Not_Applicable,Pasture,...,0.08,8129.0,0.322724,52.0,294.40,0.207067,380.75,1.322496,1323.662105,-0.196752

### Exercise 3: Unique identifiers
- Which column represents the plot and the subplot?
- How many subplots are there per plot?
- Why are there some subplots with 18 records?
- Which plots have 18 records?
- What should we do with those records?

### Fixing the duplicated sampleids
#### There are many ways to address the duplicated (QAQC) plots. In this example we are going to just use the first sample collected.

In [36]:
df3=df2.groupby(['plotid','sampleid']).first()#make sure to group on both plotid and sampleid to get all unique combinations
df3

                      Use       Cover      Vegetation        Herbaceous  \
plotid sampleid
2      5         Pasture   Vegetation       Herbaceas  Gramineous Plant
       6         Pasture   Vegetation       Herbaceas  Gramineous Plant
       7           Forest  Vegetation            Tree    Not_Applicable
       8         Pasture   Vegetation       Herbaceas  Gramineous Plant
       9           Forest  Vegetation            Tree    Not_Applicable
...                   ...         ...             ...               ...
910231 3640925     Forest  Vegetation            Tree    Not_Applicable
       3640926    WetLand       Water  Not_Applicable    Not_Applicable
       3640927     Forest  Vegetation            Tree    Not_Applicable
       3640928     Forest  Vegetation            Tree    Not_Applicable
       3640929    WetLand       Water  Not_Applicable    Not_Applicable

                                   Grass     Cultivation         WetLand  \
plotid sampleid
2      5         Pasture  Pure (90-100%)  Not_Applicable  Not_Applicable
       6         Pasture  Pure (90-100%)  Not_Applicable  Not_Applicable
       7                  Not_Applicable  Not_Applicable  Not_Applicable
       8         Pasture  Pure (90-100%)  Not_Applicable  Not_Applicable
       9                  Not_Applicable  Not_Applicable  Not_Applicable
...                                  ...             ...             ...
910231 3640925            Not_Applicable  Not_Applicable  Not_Applicable
       3640926            Not_Applicable  Not_Applicable    Water Bodies
       3640927            Not_Applicable  Not_Applicable  Not_Applicable
       3640928            Not_Applicable  Not_Applicable  Not_Applicable
       3640929            Not_Applicable  Not_Applicable    Water Bodies

                  Terrain             Water   Another Class  ...    lai  \
plotid sampleid                                              ...
2      5         Pasture     Not_Applicable  Not_Applicable  ...  0.295
       6         Pasture     Not_Applicable  Not_Applicable  ...  0.295
       7           Forest    Not_Applicable  Not_Applicable  ...  0.295
       8         Pasture     Not_Applicable  Not_Applicable  ...  0.295
       9           Forest    Not_Applicable  Not_Applicable  ...  0.295
...                   ...               ...             ...  ...    ...
910231 3640925     Forest    Not_Applicable  Not_Applicable  ...  0.595
       3640926    WetLand    Continental     Not_Applicable  ...  0.595
       3640927     Forest    Not_Applicable  Not_Applicable  ...  0.595
       3640928     Forest    Not_Applicable  Not_Applicable  ...  0.595
       3640929    WetLand    Continental     Not_Applicable  ...  0.595

                   mTPI      ndvi ocs_1mMed  sand_1mMed      savi  \
plotid sampleid
2      5         8170.0  0.687111      55.0      292.90  0.337061
       6         8128.0  0.586939      55.0      292.90  0.373690
       7         8128.0  0.772427      55.0      292.90  0.453859
       8         8170.0  0.590017      55.0      292.90  0.319073
       9         8128.0  0.744990      55.0      292.90  0.385159
...                 ...       ...       ...         ...       ...
910231 3640925   8127.0  0.931607      61.0      241.35  0.542267
       3640926   8129.0  0.218692      57.0      218.95  0.016753
       3640927   8132.0  0.937347       0.0        0.00  0.600230
       3640928   8132.0  0.931012       0.0        0.00  0.597709
       3640929   8130.0  0.448587      60.0      237.80  0.034665

                 Yeslt_1mMed      slope       topDiv   wetness
plotid sampleid
2      5               312.2  22.035748  1324.032168 -0.075597
       6               312.2  21.248732  1324.003771 -0.134302
       7               312.2  27.675804  1324.003771 -0.036954
       8               312.2   9.241508  1324.032168 -0.111264
       9               312.2  28.653061  1324.003771 -0.028836
...                      ...        ...          ...       ...
910231 3640925         390.8  11.585829  1323.701292  0.043989
       3640926         378.6   8.742791  1323.719615  0.006947
       3640927           0.0   8.742789  1323.702767  0.051642
       3640928           0.0   8.742789  1323.702767  0.061619
       3640929         393.4   7.437231  1323.709572  0.008270

[100551 rows x 42 columns]

### Exercise 4: Addressing duplicate samples
- How many subplots were removed?
- Does the total number of records make sense?
- Select for the last value. Do you get the same number of records?
- Can you think of another way to remove duplicated records?

## Aggregating to the plot

In [ ]:
UseResp=pd.crosstab(df['plotid'],df['Use'],normalize='index')#percentage by use class
pred_agg=df[['plotid']+pred].groupby('plotid').agg(['mean','std'])
pred_agg.columns = ["_".join(a) for a in pred_agg.columns.to_flat_index()] #change the multilevel index to a single level index to merger DataFrames

### Merge the percent use columns with the mean and standard deviation of aggregated subplots to create a cleaned data frame

In [49]:
clean_df=UseResp.merge(pred_agg,left_on='plotid',right_on='plotid')
clean_df

,Agriculture,Another_Class,Forest,Forest Plantation,No Information,Not_Applicable,Pasture,WetLand,BLUE_mean,BLUE_std,...,savi_mean,savi_std,Yeslt_1mMed_mean,Yeslt_1mMed_std,slope_mean,slope_std,topDiv_mean,topDiv_std,wetness_mean,wetness_std
plotid,,,,,,,,,,,,,,,,,,,,,
2,0.000000,0.000000,0.555556,0.0,0.0,0.0,0.444444,0.000000,0.024923,0.009956,...,0.408261,0.070594,303.983333,12.325000,23.399585,6.460880,1324.013237,0.014198,-0.045638,0.051034
3,0.000000,0.000000,1.000000,0.0,0.0,0.0,0.000000,0.000000,0.017278,0.000979,...,0.597643,0.031956,315.700000,6.150000,16.263312,7.074182,1324.134220,0.015620,0.004323,0.004060
4,0.000000,0.000000,0.555556,0.0,0.0,0.0,0.444444,0.000000,0.018176,0.002039,...,0.540377,0.025248,308.766667,6.550000,7.020475,3.295677,1324.042068,0.000000,-0.000462,0.020996
5,0.000000,0.111111,0.111111,0.0,0.0,0.0,0.777778,0.000000,0.028858,0.006807,...,0.477524,0.052251,325.866667,9.296505,6.548996,3.949138,1323.997239,0.000000,-0.043645,0.011165
6,0.000000,0.000000,0.888889,0.0,0.0,0.0,0.111111,0.000000,0.016862,0.001779,...,0.472229,0.025022,307.305556,11.911246,16.040434,4.771417,1324.037398,0.019349,-0.004902,0.011784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910169,0.000000,0.000000,1.000000,0.0,0.0,0.0,0.000000,0.000000,0.019328,0.002138,...,0.581225,0.033420,320.050000,0.000000,9.077526,4.104058,1323.853195,0.000000,0.015756,0.012339
910176,0.000000,0.000000,0.333333,0.0,0.0,0.0,0.666667,0.000000,0.025659,0.003147,...,0.593661,0.026421,263.000000,0.000000,10.361667,4.189221,1324.367377,0.000000,-0.016050,0.018704
910188,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,1.000000,0.056761,0.005731,...,-0.021881,0.091914,0.000000,0.000000,5.944314,4.787650,1323.705560,0.000000,0.069922,0.030923
910230,0.555556,0.000000,0.444444,0.0,0.0,0.0,0.000000,0.000000,0.035816,0.013088,...,0.426823,0.099058,456.600000,2.025000,6.798617,3.025853,1323.698868,0.000975,-0.059507,0.058697
910231,0.000000,0.000000,0.666667,0.0,0.0,0.0,0.000000,0.333333,0.009104,0.002050,...,0.373434,0.265754,301.533333,171.039791,9.287156,1.840494,1323.706611,0.007824,0.034302,0.020720

### Exercise 5: Summarizing plots
- For each response variable create a clean percent category data frame with summarized mean, standard deviation, min, and max values. How many predictor variables do you have?